
required = [
  # Needed for build
  "github.com/jteeuwen/go-bindata/go-bindata",

  # Needed for apimachinery generation
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",

  # Needed for docs generation
  "k8s.io/code-generator/cmd/openapi-gen",
  "github.com/kubernetes-incubator/apiserver-builder/cmd/apiserver-boot",
  "github.com/kubernetes-incubator/apiserver-builder/cmd/apiregister-gen",
  "github.com/kubernetes-incubator/reference-docs/gen-apidocs",

  # Needed for bazel generation / verification
  "github.com/bazelbuild/bazel-gazelle/cmd/gazelle",

  # Needed for spell checking
  "github.com/client9/misspell/cmd/misspell",
]

[prune]
  go-tests = true
  unused-packages = true

  # Don't prune helper scripts from code-generator
  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    non-go = false

[[override]]
  name = "github.com/bazelbuild/bazel-gazelle"
  version = "0.14.0"

# aws-sdk-go is one of our critical dependencies
[[override]]
  name = "github.com/aws/aws-sdk-go"
  revision = "bf8067ceb6e7f51e150c218972dccfeeed892b85"

# We need this for our build
[[override]]
  name = "github.com/jteeuwen/go-bindata"
  revision = "a0ff2567cfb70903282db057e799fd826784d41d"

# Core kubernetes components
[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.11.3"
[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.3"
[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.3"
[[override]]
  name = "k8s.io/utils"
  revision = "cd34563cd63c2bd7c6fe88a73c4dcf34ed8a67cb" # Latest
[[override]]
  name = "k8s.io/kube-openapi"
  revision = "91cfa479c814065e420cee7ed227db0f63a5854e" # version specified in 1.11.3
[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.3"
[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.11.3"
[[override]]
  name = "k8s.io/metrics"
  version = "kubernetes-1.11.3"
[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.11.3"
[[override]]
  name = "k8s.io/kubernetes"
  version = "v1.11.3"

# Needed for docs generation
[[override]]
  name = "github.com/kubernetes-incubator/apiserver-builder"
  revision = "e809ac2f9f0c238f08d08a876f8b3f499604f941"
[[override]]
  name = "github.com/kubernetes-incubator/reference-docs"
  revision = "8fadf91876ccbcfec367b434706a3c449073b0b4"


# These come from godeps.json in kubernetes
[[override]]
  name = "k8s.io/gengo"
  revision = "01a732e01d00cb9a81bb0ca050d3e6d2b947927b"
[[override]]
  name = "github.com/hashicorp/hcl"
  revision = "d8c773c4cba11b11539e3d45f93daeaa5dcf1fa1"
[[override]]
  name = "github.com/spf13/cobra"
  revision = "c439c4fa093711d42e1b01acb1235b52004753c1"
[[override]]
  name = "golang.org/x/crypto"
  revision = "49796115aa4b964c318aad4f3084fdb41e9aa067"
[[override]]
  name = "github.com/go-openapi/analysis"
  revision = "b44dc874b601d9e4e2f6e19140e794ba24bead3b"
[[override]]
  name = "github.com/go-openapi/spec"
  revision = "1de3e0542de65ad8d75452a595886fdd0befb363"
[[override]]
  name = "github.com/go-openapi/loads"
  revision = "a80dea3052f00e5f032e860dd7355cd0cc67e24d"
[[override]]
  name = "github.com/go-openapi/strfmt"
  revision = "d65c7fdb29eca313476e529628176fe17e58c488"
[[override]]
  name = "github.com/go-openapi/swag"
  revision = "f3f9494671f93fcff853e3c6e9e948b3eb71e590"
[[override]]
  name = "github.com/gogo/protobuf"
  revision = "c0656edd0d9eab7c66d1eb0c568f9039345796f7"
[[override]]
  name = "golang.org/x/sys"
  revision = "95c6576299259db960f6c5b9b69ea52422860fce"
[[override]]
  name = "github.com/gregjones/httpcache"
  revision = "787624de3eb7bd915c329cba748687a3b22666a6"
[[override]]
  name = "gopkg.in/gcfg.v1"
  revision = "27e4946190b4a327b539185f2b5b1f7c84730728"
# UNKNOWN dep github.com/tent/http-link-go
[[override]]
  name = "github.com/go-openapi/jsonreference"
  revision = "13c6e3589ad90f49bd3e3bbe2c2cb3d7a4142272"
[[override]]
  name = "github.com/docker/docker"
  revision = "4f3616fb1c112e206b88cb7a9922bf49067a7756"
[[override]]
  name = "github.com/fatih/camelcase"
  revision = "f6a740d52f961c60348ebb109adde9f4635d7540"
[[override]]
  name = "github.com/NYTimes/gziphandler"
  revision = "56545f4a5d46df9a6648819d1664c3a03a13ffdb"
[[override]]
  name = "github.com/renstrom/dedent"
  revision = "020d11c3b9c0c7a3c2efcc8e5cf5b9ef7bcea21f"
[[override]]
  name = "gopkg.in/warnings.v0"
  revision = "8a331561fe74dadba6edfc59f3be66c22c3b065d"
[[override]]
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"
[[override]]
  name = "github.com/PuerkitoBio/purell"
  revision = "8a290539e2e8629dbc4e6bad948158f790ec31f4"
[[override]]
  name = "github.com/prometheus/client_model"
  revision = "fa8ad6fec33561be4280a8f0514318c79d7f6cb6"
[[override]]
  name = "github.com/googleapis/gnostic"
  revision = "0c5108395e2debce0d731cf0287ddf7242066aba"
[[override]]
  name = "github.com/inconshreveable/mousetrap"
  revision = "76626ae9c91c4f2a10f34cad8ce83ea42c93bb75"
[[override]]
  name = "google.golang.org/api"
  revision = "8e296ef260056b6323d10727db40512dac6d92d5"
# UNKNOWN dep github.com/petar/GoLLRB
[[override]]
  name = "github.com/Microsoft/go-winio"
  revision = "78439966b38d69bf38227fbf57ac8a6fee70f69a"
[[override]]
  name = "github.com/pkg/sftp"
  revision = "4d0e916071f68db74f8a73926335f809396d6b42"
[[override]]
  name = "github.com/pborman/uuid"
  revision = "ca53cad383cad2479bbba7f7a1a05797ec1386e4"
[[override]]
  name = "github.com/vmware/govmomi"
  revision = "e70dd44f80baf671099254d675eb278529038234"
[[override]]
  name = "github.com/coreos/go-systemd"
  revision = "48702e0da86bd25e76cfef347e2adeb434a0d0a6"
[[override]]
  name = "github.com/PuerkitoBio/urlesc"
  revision = "5bd2802263f21d8788851d5305584c82a5c75d7e"
[[override]]
  name = "github.com/google/btree"
  revision = "7d79101e329e5a3adf994758c578dab82b90c017"
[[override]]
  name = "github.com/docker/spdystream"
  revision = "449fdfce4d962303d702fec724ef0ad181c92528"
[[override]]
  name = "github.com/dgrijalva/jwt-go"
  revision = "01aeca54ebda6e0fbfafd0a524d234159c05ec20"
[[override]]
  name = "github.com/russross/blackfriday"
  revision = "300106c228d52c8941d4b3de6054a6062a86dda3"
[[override]]
  name = "github.com/fsnotify/fsnotify"
  revision = "f12c6236fe7b5cf6bcf30e5935d08cb079d78334"
[[override]]
  name = "github.com/coreos/go-semver"
  revision = "568e959cd89871e61434c1143528d9162da89ef2"
[[override]]
  name = "google.golang.org/grpc"
  revision = "5b3c4e850e90a4cf6a20ebd46c8b32a0a3afcb9e"
[[override]]
  name = "golang.org/x/oauth2"
  revision = "a6bd8cefa1811bd24b86f8902872e4e8225f74c4"
# UNKNOWN dep github.com/aokoli/goutils
[[override]]
  name = "github.com/MakeNowJust/heredoc"
  revision = "bb23615498cded5e105af4ce27de75b089cbe851"
[[override]]
  name = "github.com/cpuguy83/go-md2man"
  revision = "71acacd42f85e5e82f70a55327789582a5200a90"
[[override]]
  name = "github.com/ugorji/go"
  revision = "ded73eae5db7e7a0ef6f55aace87a2873c5d2b74"
[[override]]
  name = "github.com/elazarl/go-bindata-assetfs"
  revision = "3dcc96556217539f50599357fb481ac0dc7439b9"
# UNKNOWN dep github.com/google/go-querystring
[[override]]
  name = "github.com/imdario/mergo"
  revision = "6633656539c1639d9d78127b7d47c622b5d7b6dc"
[[override]]
  name = "google.golang.org/genproto"
  revision = "09f6ed296fc66555a25fe4ce95173148778dfa85"
[[override]]
  name = "github.com/pkg/errors"
  revision = "645ef00459ed84a119197bfb8d8205042c6df63d"
[[override]]
  name = "github.com/golang/glog"
  revision = "44145f04b68cf362d9c4df2182967c2275eaefed"
[[override]]
  name = "github.com/docker/go-units"
  revision = "9e638d38cf6977a37a8ea0078f3ee75a7cdb2dd1"
[[override]]
  name = "github.com/Azure/go-ansiterm"
  revision = "19f72df4d05d31cbe1c56bfc8045c96babff6c7e"
[[override]]
  name = "github.com/Azure/go-autorest"
  revision = "1ff28809256a84bb6966640ff3d0371af82ccba4"
[[override]]
  name = "golang.org/x/net"
  revision = "1c05540f6879653db88113bc4a2b70aec4bd491f"
[[override]]
  name = "golang.org/x/text"
  revision = "b19bf474d317b857955b12035d2c5acb57ce8b01"
[[override]]
  name = "gopkg.in/yaml.v2"
  revision = "670d4cfef0544295bc27a114dbac37980d83185a"
[[override]]
  name = "gopkg.in/natefinch/lumberjack.v2"
  revision = "20b71e5b60d756d3d2f80def009790325acc2b23"
[[override]]
  name = "github.com/google/cadvisor"
  revision = "de723a090f4dd5390dc7c2acee37ba9c62f0cc09"
[[override]]
  name = "gopkg.in/inf.v0"
  revision = "3887ee99ecf07df5b447e9b00d9c0b2adaa9f3e4"
[[override]]
  name = "github.com/mitchellh/mapstructure"
  revision = "53818660ed4955e899c0bcafa97299a388bd7c8e"
[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"
[[override]]
  name = "github.com/spf13/jwalterweatherman"
  revision = "33c24e77fb80341fe7130ee7c594256ff08ccc46"
# UNKNOWN dep google.golang.org/appengine
[[override]]
  name = "github.com/spf13/viper"
  revision = "7fb2782df3d83e0036cc89f461ed0422628776f4"
[[override]]
  name = "github.com/spf13/afero"
  revision = "b28a7effac979219c2a2ed6205a4d70e4b1bcd02"
[[override]]
  name = "github.com/peterbourgon/diskv"
  revision = "5f041e8faa004a95c88a202771f4cc3e991971e6"
[[override]]
  name = "github.com/prometheus/common"
  revision = "13ba4ddd0caa9c28ca7b7bffe1dfa9ed8d5ef207"
[[override]]
  name = "github.com/spf13/cast"
  revision = "e31f36ffc91a2ba9ddb72a4b6a607ff9b3d3cb63"
[[override]]
  name = "github.com/pelletier/go-toml"
  revision = "16398bac157da96aa88f98a2df640c7f32af1da2"
[[override]]
  name = "github.com/google/gofuzz"
  revision = "44d81051d367757e1c7c6a5a86423ece9afcf63c"
[[override]]
  name = "github.com/golang/protobuf"
  revision = "b4deda0973fb4c70b50d226b1af49f3da59f5265"
[[override]]
  name = "github.com/jonboulle/clockwork"
  revision = "72f9bd7c4e0c2a40055ab3d0f09654f730cce982"
[[override]]
  name = "github.com/go-openapi/errors"
  revision = "d24ebc2075bad502fac3a8ae27aa6dd58e1952dc"
[[override]]
  name = "github.com/go-openapi/jsonpointer"
  revision = "46af16f9f7b149af66e5d1bd010e3574dc06de98"
[[override]]
  name = "github.com/prometheus/client_golang"
  revision = "e7e903064f5e9eb5da98208bae10b475d4db0f8c"
[[override]]
  name = "github.com/spf13/pflag"
  revision = "583c0c0531f06d5278b7d917446061adc344b5cd"
[[override]]
  name = "github.com/jmespath/go-jmespath"
  revision = "0b12d6b521d83fc7f755e7cfc1b1fbdd35a01a74"
[[override]]
  name = "github.com/prometheus/procfs"
  revision = "65c1f6f8f0fc1e2185eb9863a3bc751496404259"
[[override]]
  name = "github.com/matttproud/golang_protobuf_extensions"
  revision = "fc2b8d3a73c4867e51861bbdd5ae3c1f0869dd6a"
[[override]]
  name = "github.com/ghodss/yaml"
  revision = "73d445a93680fa1a78ae23a5839bad48f32ba1ee"
[[override]]
  name = "github.com/emicklei/go-restful-swagger12"
  revision = "dcef7f55730566d41eae5db10e7d6981829720f6"
[[override]]
  name = "github.com/beorn7/perks"
  revision = "3ac7bf7a47d159a033b107610db8a1b6575507a4"
[[override]]
  name = "github.com/blang/semver"
  revision = "b38d23b8782a487059e8fc8773e9a5b228a77cb6"
[[override]]
  name = "github.com/docker/go-connections"
  revision = "3ede32e2033de7505e6500d6c868c2b9ed9f169d"
# UNKNOWN dep github.com/coredns/coredns
[[override]]
  name = "github.com/magiconair/properties"
  revision = "61b492c03cf472e0c6419be5899b8e0dc28b1b88"
[[override]]
  name = "github.com/golang/groupcache"
  revision = "02826c3e79038b59d737d3b1c0a1d937f71a4433"
[[override]]
  name = "cloud.google.com/go"
  revision = "3b1ae45394a234c385be014e9a488f2bb6eef821"
[[override]]
  name = "github.com/daviddengcn/go-colortext"
  revision = "511bcaf42ccd42c38aba7427b6673277bf19e2a1"
[[override]]
  name = "github.com/miekg/dns"
  revision = "5d001d020961ae1c184f9f8152fdc73810481677"
[[override]]
  name = "github.com/juju/ratelimit"
  revision = "5b9ff866471762aa2ab2dced63c9fb6f53921342"
[[override]]
  name = "github.com/davecgh/go-spew"
  revision = "782f4967f2dc4564575ca782fe2d04090b5faca8"
[[override]]
  name = "github.com/mailru/easyjson"
  revision = "2f5df55504ebc322e4d52d34df6a1f5b503bf26d"
[[override]]
  name = "github.com/emicklei/go-restful"
  revision = "ff4f55a206334ef123e4f79bbf348980da81ca46"
[[override]]
  name = "github.com/hashicorp/golang-lru"
  revision = "a0d98a5f288019575c6d1f4bb1573fef2d1fcdc4"
[[override]]
  name = "github.com/coreos/etcd"
  revision = "95a726a27e09030f9ccbd9982a1508f5a6d25ada"
[[override]]
  name = "vbom.ml/util"
  revision = "db5cfe13f5cc80a4990d98e2e1b0707a4d1a5394"
[[override]]
  name = "github.com/client9/misspell"
  revision = "9ce5d979ffdaca6385988d7ad1079a33ec942d20"
[[override]]
  name = "github.com/stretchr/testify"
  revision = "c679ae2cc0cb27ec3293fea7e254e47386f05d69"
[[override]]
  name = "github.com/asaskevich/govalidator"
  revision = "593d64559f7600f29581a3ee42177f5dbded27a9"
[[override]]
  name = "github.com/evanphx/json-patch"
  revision = "94e38aa1586e8a6c8a75770bddf5ff84c48a106b"
[[override]]
  name = "github.com/pmezard/go-difflib"
  revision = "d8ed2627bdf02c080bf22230dbb337003b7aba2d"


# These are our dependencies, with the versions we previously locked to with submodules
[[override]]
  name = "github.com/Masterminds/semver"
  revision = "517734cc7d6470c0d07130e40fd40bdeb9bcd3fd"
[[override]]
  name = "github.com/Masterminds/sprig"
  revision = "e039e20e500c2c025d9145be375e27cf42a94174"
[[override]]
  name = "github.com/coreos/pkg"
  revision = "fa29b1d70f0beaddd4c7021607cc3c3be8ce94b8"
[[override]]
  name = "github.com/digitalocean/godo"
  revision = "34840385860db94c88d044571153b6a200ca40b2"
[[override]]
  name = "github.com/docker/engine-api"
  revision = "dea108d3aa0c67d7162a3fd8aa65f38a430019fd"
[[override]]
  name = "github.com/grpc-ecosystem/go-grpc-prometheus"
  revision = "2500245aa6110c562d17020fb31a2c133d737799"
[[override]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  revision = "8cc3a55af3bcf171a1c23a90c4df9cf591706104"
[[override]]
  name = "github.com/huandu/xstrings"
  revision = "3959339b333561bf62a38b424fd41517c2c90f40"
[[override]]
  name = "github.com/miekg/coredns"
  revision = "20e25559d5eada5a68a0720816a6e947b94860ce"
[[override]]
  name = "github.com/opencontainers/go-digest"
  revision = "a6d0ee40d4207ea02364bd3b9e8e77b9159ba1eb"
[[override]]
  name = "github.com/opencontainers/image-spec"
  revision = "372ad780f63454fbbbbcc7cf80e5b90245c13e13"
[[override]]
  name = "github.com/pelletier/go-buffruneio"
  revision = "df1e16fde7fc330a0ca68167c23bf7ed6ac31d6d"
[[override]]
  name = "github.com/sergi/go-diff"
  revision = "552b4e9bbdca9e5adafd95ee98c822fdd11b330b"
[[override]]
  name = "github.com/shurcooL/sanitized_anchor_name"
  revision = "10ef21a441db47d8b13ebcc5fd2310f636973c77"
[[override]]
  name = "github.com/sirupsen/logrus"
  revision = "89742aefa4b206dcf400792f3bd35b542998eb3b"
[[override]]
  name = "github.com/weaveworks/mesh"
  revision = "1f158d31de55abf9f97bbaa0a260e2b8023a3785"



# We have some newer versions than kubernetes/kubernetes godeps
[[override]]
  name = "github.com/satori/go.uuid"
  revision = "5bf94b69c6b68ee1b541973bb8e1144db23a194b"
[[override]]
  name = "golang.org/x/time"
  revision = "fbb02b2291d28baffd63558aa44b4b56f178d650"
[[override]]
  name = "golang.org/x/tools"
  revision = "2382e3994d48b1d22acc2c86bcad0a2aff028e32"
[[override]]
  # The older version (c6fed...) specified in k8s.io/kubernetes Godeps breaks go dep
  name = "github.com/chai2010/gettext-go"
  revision = "bf70f2a70fb1b1f36d90d671a72795984eab0fcb"
[[override]]
  name = "gopkg.in/square/go-jose.v2"
  revision = "76dd09796242edb5b897103a75df2645c028c960"
[[override]]
  name = "github.com/gophercloud/gophercloud"
  revision = "f29afc2cceca860199ee88cd355a4d0a37b3fad2"
