managedFile/{{ ClusterName }}-addons-bootstrap-kube-dns:
  location: addons/kube-dns/v1.4.0.yaml
  contents: resources/addons/kube-dns/v1.4.0.yaml

managedFile/{{ ClusterName }}-addons-bootstrap-core:
  location: addons/core/v1.4.0.yaml
  contents: resources/addons/core/v1.4.0.yaml

managedFile/{{ ClusterName }}-addons-bootstrap-dns-controller:
  location: addons/dns-controller/v1.4.1.yaml
  contents: resources/addons/dns-controller/v1.4.1.yaml
