---
name: CI

'on':
  - push
  - pull_request

env:
  GOPROXY: https://proxy.golang.org
  GOPATH: ${{ github.workspace }}/go

jobs:
  build-linux-amd64:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.1

      - uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/k8s.io/kops

      - name: make all examples test
        working-directory: ${{ env.GOPATH }}/src/k8s.io/kops
        run: |
          make all examples test

  build-macos-amd64:
    runs-on: macos-10.15
    steps:
    - name: Set up go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.1

    - uses: actions/checkout@v2
      with:
        path: ${{ env.GOPATH }}/src/k8s.io/kops

    - name: make kops examples test
      working-directory: ${{ env.GOPATH }}/src/k8s.io/kops
      run: |
        make kops examples test

  build-windows-amd64:
    runs-on: windows-2019
    steps:
    - name: Set up go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.1

    - uses: actions/checkout@v2
      with:
        path: ${{ env.GOPATH }}/src/k8s.io/kops

    - name: make kops examples test
      working-directory: ${{ env.GOPATH }}/src/k8s.io/kops
      run: |
        make kops examples test-windows

  verify:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.1

      - uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/k8s.io/kops

      - name: make travis-ci
        working-directory: ${{ env.GOPATH }}/src/k8s.io/kops
        run: |
          make travis-ci
