---
name: CI

"on":
  - push
  - pull_request

env:
  GOPROXY: https://proxy.golang.org
  GOPATH: ${{ github.workspace }}/go

permissions:
  contents: read

jobs:
  build-linux:
    strategy:
      matrix:
        os:
          - name: Linux-amd64
            runs-on: ubuntu-24.04
            arch: amd64
          - name: Linux-arm64
            runs-on: ubuntu-24.04-arm
            arch: arm64
    name: build-linux-${{ matrix.os.arch }}
    runs-on: ${{ matrix.os.runs-on }}
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
        with:
          path: ${{ env.GOPATH }}/src/k8s.io/kops

      - name: Set up go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
        with:
          go-version-file: "${{ env.GOPATH }}/src/k8s.io/kops/go.mod"

      - name: make all examples test
        working-directory: ${{ env.GOPATH }}/src/k8s.io/kops
        run: |
          make all examples test

  build-macos-amd64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
        with:
          path: ${{ env.GOPATH }}/src/k8s.io/kops

      - name: Set up go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
        with:
          go-version-file: "${{ env.GOPATH }}/src/k8s.io/kops/go.mod"

      - name: make kops examples test
        working-directory: ${{ env.GOPATH }}/src/k8s.io/kops
        run: |
          make kops examples test

  build-windows-amd64:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
        with:
          path: ${{ env.GOPATH }}/src/k8s.io/kops

      - name: Set up go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
        with:
          go-version-file: "${{ env.GOPATH }}/src/k8s.io/kops/go.mod"

      - name: make kops examples test
        working-directory: ${{ env.GOPATH }}/src/k8s.io/kops
        run: |
          make kops examples test-windows

  verify:
    strategy:
      matrix:
        os:
          - name: Linux-amd64
            runs-on: ubuntu-24.04
            arch: amd64
          - name: Linux-arm64
            runs-on: ubuntu-24.04-arm
            arch: arm64
    name: verify-${{ matrix.os.arch }}
    runs-on: ${{ matrix.os.runs-on }}
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
        with:
          path: ${{ env.GOPATH }}/src/k8s.io/kops

      - name: Set up go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
        with:
          go-version-file: "${{ env.GOPATH }}/src/k8s.io/kops/go.mod"

      - name: make quick-ci
        working-directory: ${{ env.GOPATH }}/src/k8s.io/kops
        run: |
          make quick-ci
