name: 'Tag Release'

on:
  push:
    branches:
      - master
      - 'release-*'
    paths:
      - kops-version.go

jobs:
  tag-release:
    if: ${{ github.repository == 'kubernetes/kops' }}
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
      - run: /usr/bin/git config --global user.email actions@github.com
      - run: /usr/bin/git config --global user.name 'GitHub Actions Release Tagger'
      - run: hack/tag-release.sh
