name: 'Update Dependencies'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 5'

env:
  GOPROXY: https://proxy.golang.org

permissions:
  contents: write
  pull-requests: write

jobs:
  update-deps:
    if: ${{ github.repository == 'kubernetes/kops' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f
        with:
          go-version: '1.19.0'
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Update Dependencies
        id: update_deps
        run: |
          make depup
          echo "::set-output name=changes::$(git status --porcelain)"
      - name: Create PR
        if: ${{ steps.update_deps.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@171dd555b9ab6b18fa02519fdfacbb8bf671e1b4
        with:
          title: 'Update dependencies'
          commit-message: Update dependencies
          committer: github-actions <actions@github.com>
          author: github-actions <actions@github.com>
          branch: dependencies/update
          branch-suffix: timestamp
          base: master
          delete-branch: true
          labels: ok-to-test
          body: |
            Updating go.mod with latest dependencies...
