name: 'Update Dependencies'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 5'

env:
  GOPROXY: https://proxy.golang.org

permissions:
  contents: write
  pull-requests: write

jobs:
  update-deps:
    if: ${{ github.repository == 'kubernetes/kops' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
        with:
          go-version-file: 'go.mod'

      - name: Update Dependencies
        id: update_deps
        run: |
          make depup
          echo 'changes<<EOF' >> $GITHUB_OUTPUT
          git status --porcelain >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Create PR
        if: ${{ steps.update_deps.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c
        with:
          title: 'Update dependencies'
          commit-message: Update dependencies
          committer: github-actions <actions@github.com>
          author: github-actions <actions@github.com>
          branch: dependencies/update
          branch-suffix: timestamp
          base: master
          delete-branch: true
          labels: ok-to-test
          body: |
            Updating go.mod with latest dependencies...
