name: "update-deps"
on: [workflow_dispatch]

env:
  GOPROXY: https://proxy.golang.org

permissions:
  contents: write
  pull-requests: write

jobs:
  update-deps:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5
      - uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923
        with:
          go-version: '1.18'
      - name: Update Dependencies
        id: update_deps
        run: |
          make depup
          echo "::set-output name=changes::$(git status --porcelain)"
      - name: Create PR
        if: ${{ steps.update_deps.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@923ad837f191474af6b1721408744feb989a4c27
        with:
          title: 'Update dependencies'
          commit-message: Update dependencies
          committer: github-actions <actions@github.com>
          author: github-actions <actions@github.com>
          branch: dependencies/update
          branch-suffix: timestamp
          base: master
          delete-branch: true
          labels: ok-to-test
          body: |
            Updating go.mod with latest dependencies:
            ```
            ${{ join(steps.update_deps.outputs.changes, "\n") }}
            ```
